name: GitHub Profile Review
description: Please review my GitHub profile 
title: "[REVIEW] <your-username>"
labels: gh profile review
body:
  - type: input
    id: link
    attributes:
      label: GitHub Profile Link
      placeholder: https://github.com/<your-username>
    validations:
      required: true
  
