name: Invitation to the ColdMold Community Organization
description: I would like to be part of the developers community
title: "Please invite me to the ColdMold Community Organization"
labels: [invite me to the organisation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      placeholder: Insert your Discord username here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: What do you like about this community/Why do you want to join?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Follow our owner's LinkedIn Page [here](https://www.linkedin.com/in/anubhav-saxena-84438a249) for Internships, Jobs, Workshops, Events updates! 
